export default {
	creation: {
		ADD_OBSERVER: 'ADD_OBSERVER',
		CHOOSE_TRADE_TYPE: 'CHOOSE_TRADE_TYPE',
		SET_PRICE: 'SET_PRICE',
		SET_TRADE_PRICE: 'SET_TRADE_PRICE',
		SET_MESSAGE: 'SET_MESSAGE',
		FINISH: 'FINISH',
	},
	removal: {
		PAIRS_LIST: 'PAIRS_LIST',
		ALERTS_LIST: 'ALERTS_LIST',
	},
	default: {
		CHOOSE_PAIR_FUNC: 'CHOOSE_PAIR_FUNC',
	},
};
