export default {
  creation: {
    SYMBOL: 'TRADE_SYMBOL',
    TYPE: 'TRADE_TYPE',
    PRICE: 'TRADE_PRICE',
    FINISH: 'TRADE_FINISH',
    SHOULDER: 'TRADE_SHOULDER',
    STOP_LOSS: 'TRADE_STOP_LOSS',
    TAKE_PROFIT: 'TRADE_TAKE_PROFIT',
    SPIKING: 'TRADE_SPIKING'
  },
  removal: {
    TRADE_LIST: 'TRADE_LIST',
    REMOVE_TRADE: 'REMOVE_TRADE',
  },
  default: {
    CHOOSE_TRADE_FUNC: 'CHOOSE_TRADE_FUNC'
  }
}